//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyMember.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgencyMaster
    {
        public int AgencyMasterId { get; set; }
        public string AgencyName { get; set; }
    }
}
