//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyMember.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServiceId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public int RequestedBy { get; set; }
        public string ServiceDuration { get; set; }
        public bool IsApplicationUserNotified { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public int ServiceMasterId { get; set; }
    }
}
